rvm:
  - ruby-1.9.3
  - ruby-2.0.0

before_install: 'bundle install'
install:
  - 'git config --global user.email "travis@ci.com"'
  - 'git config --global user.name "Travis CI"'

script: 'bundle exec rspec spec'
